version: '3.7'

services:
  database:
    image: postgres:15.5-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - db

  api:
    image: ${DOCKER_IMAGE}
    container_name: ${CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    expose:
      - 3333
    networks:
      - qualitygate
      - db

volumes:
  pg_data:

networks:
  qualitygate:
    external: true
  db:
